version: '3.4'

services:
  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "Test Cluster"
      CASSANDRA_NUM_TOKENS: "256"
      MAX_HEAP_SIZE: "512M"
      HEAP_NEWSIZE: "100M"

  productservice:
    image: productservice
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - cassandra
    ports:
      - "5000:80"
